Add ui feature
AY1920S1-CS2103T-F14-4/main pull request #115
Opened 2019-10-24 15:59 UTC by ArgVampir

2019-10-25 10:04 UTC, tysg requested changes
Good job on getting the UI to work! Just a few things to address...

2019-10-25 10:04 UTC, tysng commented on src/main/java/seedu/address/ui/TaskListPanel.java
> +    private final Logger logger = LogsCenter.getLogger(TaskListPanel.class);
Logger seems to be irrelevant? I'm not very familiar with the UI code, so disregard this if I'm wrong.

2019-10-28 16:22 UTC, junnbang commented
Kris: view command unfinished

2019-10-28 16:23 UTC, junnbang submitted a review, later dismissed
looks good

2019-10-29 06:30 UTC, tysg approved these changes

2019-10-29 06:41 UTC, merged